#----------------------------------------------------------------
# The utilities of generating the dataset used in monte calro
# simulations of Funk et al.(2011).
#----------------------------------------------------------------

GenerateStandardNormalSamples <- function (size) {
  # Generates samples from standard normal distribution.
  #
  # Args:
  #   size: Sample size to be generated.
  #
  # Returns:
  #   A generated sample.
  rnorm(n = size, mean = 0, sd = 1)
}


GenerateDichotomosRandomSamples <- function (size, criteria = 0.3) {
  # Generates a sample from dichotomos random distribution.
  #
  # Notes:
  #   The dichotomos random distribution is defined in Web Appendix 3 of Funk et al.(2011).
  #
  # Args:
  #   size: Sample size to be generated.
  #   criteria: Control the ratio of number of 1's in the sample. Default is 0.3.
  #             Each element will be assigned to 1 if a random number, which is from
  #             uniform distribution between 0 to 1 is less than or equal to criteria.
  #
  # Returns:
  #   A generated sample.
  uniform.samples <- runif(n = size)
  dichotomos.samples <- as.numeric(uniform.samples <= criteria)

  dichotomos.samples
}


CalculateTruePropensityScores <- function (z1, z2, z3,
                                           b0 = 1.5, b1 = 1, b2 = -2, b3 = 1) {
  # Calculate the propensity scores with the model of Funk et al.(2011).
  #
  # Model definition:
  #   The true propensity score model is as followed:
  #       P(X=1 | Z) = (1 + exp{-(b0 + b1*z1 + b2*z2 + b3*z3)})^(-1),
  #   where b0 = 1.5, b1 = 1, b2 = -2, b3 = 1.
  #
  # Args:
  #   z1: Random numbers from standard normal variables.
  #   z2: Random numbers from standard normal variables. This must not be same.
  #   z3: Random numbers generated by GenerateDichotomosRandomSamples.
  #   b0: A coefficient. Default is 1.5.
  #   b1: A coefficient for z1. Default is 1.
  #   b2: A coefficient for z2. Default is -2.
  #   b3: A coefficient for z3. Default is 1.
  #
  # Returns:
  #   The propensity scores.
  propensity.scores <- (1 + exp(-(b0 + b1 * z1 + b2 * z2 + b3 * z3)))^(-1)

  propensity.scores
}


GenerateExposureVariables <- function (propensity.scores, criteria = 0.91) {
  # Generate exposure variables.
  #
  # Args:
  #   propensity.scores: Propensity scores to be used in generating exposure variables.
  #   criteria: Criteria to dichotomize resulting exposure variables. Default is 0.91.
  #
  # Returns:
  #   A list composed to exposure variables and noises which were used in
  #   generating exposure variables.
  size <- length(propensity.scores)
  noise <- runif(size)
  exposure.variables <- as.numeric((propensity.scores + noise) <= criteria)

  result <- list(exposure = exposure.variables, noise = noise)

  result
}


GenerateOutcomeVariables <- function (z1, z3,
                                      b1 = 1, b3 = 1, b4 = 2) {
  # Generate the outcome variables.
  #
  # Args:
  #  z1: Random numbers from standard normal variables.
  #  z3: Random numbers generated by GenerateDichotomosRandomSamples.
  #
  # Returns:
  #   A list composed to outcome variables and z4 which was used in
  #   generating outcome variables.
  z4 <- GenerateStandardNormalSamples(size = length(z1))
  outcome.variables <- b1 * z1 + b3 * z3 + b4 * z4
  
  result <- list(outcome = outcome.variables, z4 = z4)
  
  result
}


GenerateSimulationData <- function (size) {
  # Generating the dataset to be used in monte calro simulation of Funk et al.(2011).
  # 
  # Args:
  #   size: Sample size to be generated.
  #
  # Results:
  #   A dataset to be used in simulation of Funk et al.(2011).
  z1 <- GenerateStandardNormalSamples(size)
  z2 <- GenerateStandardNormalSamples(size)
  z3 <- GenerateDichotomosRandomSamples(size)
  propensity.scores <- CalculateTruePropensityScores(z1, z2, z3)
  result.generate.exposure <- GenerateExposureVariables(propensity.scores)
  x <- result.generate.exposure$exposure
  noise <- result.generate.exposure$noise
  result.generate.outcome <- GenerateOutcomeVariables(z1, z3)
  z4 <- result.generate.outcome$z4
  y <- result.generate.outcome$outcome

  simulation.data <- data.frame(
    y                 = y,
    x                 = x,
    propensity.scores = propensity.scores,
    noise             = noise,
    z1                = z1,
    z2                = z2,
    z3                = z3,
    z4                = z4
  )
  
  simulation.data
}
